/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.sv.udb.vista;

import com.sv.udb.controlador.EquiposCtrl;
import com.sv.udb.controlador.JugadoresCtrl;
import com.sv.udb.modelo.Equipo;
import com.sv.udb.modelo.Jugadores;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author luisedu
 */
public class FrmPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form FrmPrincipal
     */
    
    int idEq = 0;
    int idJu = 0;
    EquiposCtrl equiCtrl;
    public FrmPrincipal() {
        initComponents();
        CargarValoresCombo();
        //loadTable();
        llenarTabla();
        this.equiCtrl = new EquiposCtrl();
    }
    
//    private void loadTable() {
//        List<Equipo> team = new EquiposCtrl().consTodo();
//        String[] titles = { "Nombre", "Descripción"};
//        DefaultTableModel model = new DefaultTableModel(null, titles);
//        
//        for (Equipo t : team) {
//            Object[] row = { t.getNombre(), t.getDescripcion()};
//            model.addRow(row);
//        }
//        jtbDatos.setModel(model);
//    }
    
    private void loadTableJugadores(){
        List<Jugadores> player = new JugadoresCtrl().consTodo();
        String[] titles = {"Equipo","Nombre","Edad","Altura", "Peso"};
        DefaultTableModel model = new DefaultTableModel(null, titles);
        
        for (Jugadores p : player){
            Object[] row = {p.getCodiEqui(), p, p.getEdadJuga(), p.getAltuJuga(), p.getPesoJuga()};
            model.addRow(row);
        }
        jtbJuga.setModel(model);
    }
    
    private void CargarValoresCombo()
    {
        List<Equipo> team = new EquiposCtrl().consTodo();
       
        DefaultComboBoxModel model = new DefaultComboBoxModel();
        
        for (Equipo t : team) {
            model.addElement(t);
        }
        cmbEquipo.setModel(model);
    }
    
    public void limpiarEq(){
        txtNombreEq.setText("");
        txtDescripEq.setText("");
        idEq=0;
    }
    
    private void llenarTabla() {
        try {
            DefaultTableModel model = (DefaultTableModel) this.jtbDatos.getModel();
            while (model.getRowCount() > 0) {
                model.removeRow(0);
            } //Limpiar modelo
            for (Equipo temp : new EquiposCtrl().consTodo()) {
                model.addRow(new Object[]{temp, temp.getDescripcion()});
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtNombreEq = new javax.swing.JTextField();
        txtDescripEq = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtbDatos = new javax.swing.JTable();
        btnModificarEqui = new javax.swing.JButton();
        btnEliminarEqui = new javax.swing.JButton();
        btnLimpiarEqui = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtbJuga = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        txtNombreJuga = new javax.swing.JTextField();
        txtEdadJuga = new javax.swing.JTextField();
        txtAlturaJuga = new javax.swing.JTextField();
        txtPesoJuga = new javax.swing.JTextField();
        cmbEquipo = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        btnGuarJuga = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Nombre");

        jLabel2.setText("Descripción");

        jButton1.setText("Guardar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jtbDatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Nombre", "Descripción"
            }
        ));
        jtbDatos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtbDatosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtbDatos);

        btnModificarEqui.setText("Modificar");
        btnModificarEqui.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarEquiActionPerformed(evt);
            }
        });

        btnEliminarEqui.setText("Eliminar");
        btnEliminarEqui.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarEquiActionPerformed(evt);
            }
        });

        btnLimpiarEqui.setText("Limpiar");
        btnLimpiarEqui.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarEquiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtDescripEq)
                            .addComponent(txtNombreEq, javax.swing.GroupLayout.DEFAULT_SIZE, 103, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnLimpiarEqui, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(btnModificarEqui, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnEliminarEqui, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 399, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtNombreEq, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtDescripEq, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnModificarEqui)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEliminarEqui))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnLimpiarEqui)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Equipos", jPanel1);

        jtbJuga.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Codigo", "Equipo", "Descripcion", "Nombre", "Edad", "Altura", "Peso"
            }
        ));
        jScrollPane2.setViewportView(jtbJuga);

        jLabel3.setText("Nombre");

        jLabel4.setText("Edad");

        jLabel5.setText("Altura");

        jLabel6.setText("Peso");

        jLabel7.setText("Equipo");

        btnGuarJuga.setText("Guardar");
        btnGuarJuga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuarJugaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNombreJuga)
                            .addComponent(txtAlturaJuga)
                            .addComponent(txtPesoJuga)
                            .addComponent(txtEdadJuga)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(cmbEquipo, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 55, Short.MAX_VALUE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btnGuarJuga)
                        .addGap(103, 103, 103)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 398, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cmbEquipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtNombreJuga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtEdadJuga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtAlturaJuga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtPesoJuga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnGuarJuga)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Jugadores", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 291, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        try {
            if(new EquiposCtrl().guar(this.txtNombreEq.getText(), this.txtDescripEq.getText())) {
                JOptionPane.showMessageDialog(this,"Equipo guardado correctamente", "POO1", JOptionPane.INFORMATION_MESSAGE);
                this.txtNombreEq.setText("");
                this.txtDescripEq.setText("");
                llenarTabla();
            }else{
                JOptionPane.showMessageDialog(this,"Error al guardar equipo", "POO1", JOptionPane.INFORMATION_MESSAGE);
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this,"Error al procesar", "POO1", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnGuarJugaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuarJugaActionPerformed
        // TODO add your handling code here:
        try {
            Equipo qe= (Equipo) cmbEquipo.getSelectedItem();
            if(new JugadoresCtrl().guar( qe, this.txtNombreJuga.getText(), Integer.parseInt(this.txtEdadJuga.getText()), Integer.parseInt(this.txtAlturaJuga.getText()), Integer.parseInt(this.txtPesoJuga.getText()))) {
                JOptionPane.showMessageDialog(this,"Equipo guardado correctamente", "POO1", JOptionPane.INFORMATION_MESSAGE);
                this.txtNombreEq.setText("");
                this.txtDescripEq.setText("");
                loadTableJugadores();
            }else{
                JOptionPane.showMessageDialog(this,"Error al guardar equipo", "POO1", JOptionPane.INFORMATION_MESSAGE);
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this,"Error al procesar", "POO1", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btnGuarJugaActionPerformed

    private void btnModificarEquiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarEquiActionPerformed
        // TODO add your handling code here:
        
        try {
       
        if(idEq != 0){
            if(new EquiposCtrl().modificar(idEq, txtNombreEq.getText(),txtDescripEq.getText())){
                JOptionPane.showMessageDialog(this, "Se modifico correctamente");
                limpiarEq();
                llenarTabla();
                CargarValoresCombo();
            }else{
                JOptionPane.showMessageDialog(this, "No se pudo modificar");
            }
        }else{
            JOptionPane.showMessageDialog(this, "No se ha seleccionado ningun equipo");
        }
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_btnModificarEquiActionPerformed

    private void jtbDatosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtbDatosMouseClicked
        // TODO add your handling code here:
        int row = this.jtbDatos.getSelectedRow();
        if (row >= 0) {
            Equipo obje = (Equipo) this.jtbDatos.getValueAt(row, 0);
            idEq = obje.getCodigo();
            txtNombreEq.setText(obje.getNombre()); 
            txtDescripEq.setText(obje.getDescripcion());
            
        }
    }//GEN-LAST:event_jtbDatosMouseClicked

    private void btnEliminarEquiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarEquiActionPerformed
        // TODO add your handling code here:
        if(idEq !=0){
            int dialogResult = JOptionPane.showConfirmDialog(null, "Desea eliminar el equipo?", "Warning", JOptionPane.YES_NO_OPTION);
            if (dialogResult == JOptionPane.YES_OPTION) {
                if (new EquiposCtrl().eliminar(idEq)) {
                    JOptionPane.showMessageDialog(this, "Se elimino correctamente");
                    limpiarEq();
                    llenarTabla();
                    CargarValoresCombo();
                } else {
                    JOptionPane.showMessageDialog(this, "No se pudo eliminar");
                }
            }
        } else {
            JOptionPane.showMessageDialog(this, "No se ha seleccionado ningun equipo");
        }
    }//GEN-LAST:event_btnEliminarEquiActionPerformed

    private void btnLimpiarEquiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarEquiActionPerformed
        // TODO add your handling code here:
        limpiarEq();
    }//GEN-LAST:event_btnLimpiarEquiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEliminarEqui;
    private javax.swing.JButton btnGuarJuga;
    private javax.swing.JButton btnLimpiarEqui;
    private javax.swing.JButton btnModificarEqui;
    private javax.swing.JComboBox<Equipo> cmbEquipo;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jtbDatos;
    private javax.swing.JTable jtbJuga;
    private javax.swing.JTextField txtAlturaJuga;
    private javax.swing.JTextField txtDescripEq;
    private javax.swing.JTextField txtEdadJuga;
    private javax.swing.JTextField txtNombreEq;
    private javax.swing.JTextField txtNombreJuga;
    private javax.swing.JTextField txtPesoJuga;
    // End of variables declaration//GEN-END:variables
}
